### ISSUE TITLE
timestamp of 0 posted to firebase making historical UI graphs unusable

### ISSUE THREAD

**Issue by dutchiechris** [HalleyInteractive/plant-monitor#17]
Someone I ended up with a timestamp value of 0 in my firebase database, which caused the historical graphs in the web app to be unusable.

Checking the ESP32 code I think isTimeValid [here](https://github.com/HalleyInteractive/plant-monitor/blob/master/plant-monitor.ino#L164) should catch wacky timestamps, but as-is it only logs it and then continues.

Suggest to add or modify logic to skip posting to firebase if isTimeValid is false.

Source of problem could also be that the random single NTP host from nl.pool.ntp.org reported this 0 timestamp.  If supported, maybe adding 3 hosts using the syntax [here](https://www.pool.ntp.org/zone/nl) would be more robust.

**Comment by HalleyInteractive** [comment]
Good catch, for now I've [updated](https://github.com/HalleyInteractive/plant-monitor/commit/a608da8c48593410aada495a530d5347d1a1dcbc) the code to let the ESP go back to sleep if time is invalid.
I'll see if we can fall back to another NTP host or potentially even Firebase to provide a timestamp, see example [here](https://github.com/HalleyInteractive/plant-monitor/blob/56fc4ae90be93cf4d1b95db8ee084eb16e23bda7/google-plant.ino#L95-L101)
