### ISSUE TITLE
Firebase realtime db - insecure rules

### ISSUE THREAD

**Issue by dutchiechris** [HalleyInteractive/plant-monitor#18]
Got this alert from Firebase:

![image](https://user-images.githubusercontent.com/917241/97889204-5d89a380-1d2c-11eb-9922-c7a1e8431521.png)

Any hints for rules that are safe and keep my plant health reporting alive?

**Comment by HalleyInteractive** [comment]
Ah good one indeed.
You can do the following to restrict read/write access to only your google account:

From the `Authentication` page on the first tab `Users` copy your `User UID`. 
Then on the `Realtime Database` page on the tab 'Rules' you can use the following structure to restrict reading and writing to only your users ID.

```
{
    "rules": {
        ".write": "auth.uid === 'USER UID HERE'",
      	".read": "auth.uid === 'USER UID HERE'",
        "plants": {
            "$uid": {
                "logs": {
                    ".indexOn": "timestamp"
                }
            }
        }
    }
}
```
After you made the changes you can publish them.

Let me know if this worked for you.

**Comment by dutchiechris** [comment]
I've set the rule update and incoming metrics and the dashboard still work so LGTM!  Thanks :-)
